### ISSUE TITLE
Can't make migration on installation -  with included workaround

### ISSUE THREAD

**Issue by dsbrown** [DallasMorningNews/django-rolodex#16]
#Can't make migration on installation -  with included workaround

Hi, I tried out Rolodex and I really like many things about it; but, it was very challenging to install for me. Please let me know if this is a real issue or not? First I created a blank project and app on my MacOS X development box so nothing else was interfering with Rolodex. When I did a migrate I hit the following error:
    django.db.utils.OperationalError: no such table: rolodex_p2org_type
The entire error trail is below in this issue report. 

I finally figure out the problem after a failed first attempt. I mention the first attempt in the unlikely event that it has some bearing on the solution. I knew that for some reason migrate was trying to touch the P2Org_Type table before it was being created; but I didn't know why. I first commented out the .save class extensions in the models.py class overrides, thinking that it was the super() hitting the database prematurely:
    class P2Org_Type
    class Org2Org_Type
    class P2P_Type
That didn't fix it, so I then commented out:
    #EMPLOYMENT = P2Org_Type.objects.filter(relationship_type='employment').first()
on line 22 of models.py as it was mentioned in the error trace.

It then migrated and i was able to go back and undo all my comments.
It appears to be fully working now.

My suggestion is that Django migrate may have changed since the last major release not too long ago and you may need to change the installation documentation or methodology?

#Full Error Trace
`
685b35c89b4a:contacts browdavi$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Library/Python/2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Library/Python/2.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/Library/Python/2.7/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/browdavi/Prog/contacts/contacts/urls.py", line 21, in <module>
    url(r'^rolodex/', include('rolodex.urls')),
  File "/Library/Python/2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/rolodex/urls.py", line 2, in <module>
    from rolodex import views, API
  File "/Library/Python/2.7/site-packages/rolodex/views.py", line 22, in <module>
    EMPLOYMENT = P2Org_Type.objects.filter(relationship_type='employment').first()
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 550, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: rolodex_p2org_type
`

**Comment by hobbes7878** [comment]
Hi,
I replicated this issue with Django 1.9.

One solution would be to introspect the db in `views.py` just to make sure that first migration has run. Something like this seems to do the trick:

```python
from django.db import connection

if 'rolodex_p2org' in connection.introspection.table_names():
	EMPLOYMENT = P2Org_Type.objects.filter(relationship_type='employment').first()
else:
	EMPLOYMENT = None
```

I'll mark it as a bug and hopefully roll the next release in a few days.

Thanks!
